### ISSUE TITLE
Qv2ray v2.0 alpha 1

### ISSUE THREAD

**Issue by lhy0403** [lhy0403/Qv2ray#121]
这个 issue 将用来讨论有关 **Qv2ray v2.0 alpha 1** 的 （近乎天文数字的）bug

https://github.com/lhy0403/Qv2ray/releases/tag/v1.99.2

# 测试之前请备份配置文件！

## v2.0 发布之前会大幅更改配置文件格式，请不要依赖此版本

可供测试的功能：
- [ ] 导入配置
    - [ ] 测试 “保留入站设置” 选项
    - [ ] 导入单个 vmess 链接
    - [ ] 导入多个 vmess 连接
    - [ ] 从文件选择二维码
    - [ ] 从主屏幕扫描二维码
    - [ ] 手动输入连接配置
- [ ] 配置编辑
    - [ ] Mux 配置选项
- [ ] 路由编辑
    - [ ] 添加新路由
    - [ ] 从文件添加复杂配置的出站设置 （见上 导入配置）
    - [ ] 手动添加入站设置
- [ ] 首选项页面
    - [ ] linux: tProxy 支持
    - [ ] 深色 UI 和 托盘图标
    - [ ] GNOME 自动设置代理
    - [ ] PAC 服务
    - [ ] PAC 文件内容
    - [ ] 下载 GFWList / 手动指定 GFWList 位置
    - [ ] Windows 自动设置代理
    - [ ] Plasma 和 Windows 下的 ToolBar 设置
    - [ ] UI 主题设置
- [ ] 统计功能
    - [ ] 流量统计稳定性

**Comment by lhy0403** [comment]
没有完成的功能
- [ ] 前置代理
- [ ] 订阅 添加/删除/更新

**Comment by lhy0403** [comment]
@axionl Please consider update `qv2ray-dev-git` to `v1.99.2` in AUR, Thanks

**Comment by thebadgateway** [comment]
English is not working.
[pic](https://pixs.ru/images/2019/11/27/27-NOY-2019--125044.md.png)

**Comment by lhy0403** [comment]
Let me check @thebadgateway

**Comment by lhy0403** [comment]
Seems the latest commit fixed it, it should be caused by a non-complete English translation file, `en-US`, which cannot be loaded unless it's marked as `fully translated`.

Please check if this works. https://github.com/lhy0403/Qv2ray/commit/0eca6c2260534125097b7f0a835a057b0d750dde @thebadgateway

**Comment by axionl** [comment]
> @axionl Please consider update `qv2ray-dev-git` to `v1.99.2` in AUR, Thanks

The package version number will be generated automatically by the `pkgver()` function, but I also updated the AUR.

**Comment by lhy0403** [comment]
Sure, thanks, I just received that AUR update email.

**Comment by lhy0403** [comment]
@aliyuchang33 Empty Inbound tag when calling API is now fixed!

**Comment by lhy0403** [comment]
https://t.me/joinchat/PIQvj1XMcjD6xweF2A98jw

**Comment by lhy0403** [comment]
@DuckSoft  https://github.com/lhy0403/Qv2ray/issues/69#issuecomment-534831181 #75 已经实现使用 enter 键进行连接 （首先需要使用 tab 将焦点设置于连接列表）

**Comment by lhy0403** [comment]
新版本添加了 log 颜色（emmm 就是带颜色的 log）
emmm 直接上图好了

![image](https://user-images.githubusercontent.com/18734999/69789231-18472280-11fb-11ea-89f2-49426aa95bcc.png)

**Comment by lfxx** [comment]
无法手动添加配置,添加后无反应,而且开启pac后无法登录外网

**Comment by lhy0403** [comment]
- [ ] 手动添加配置
 - [ ] PAC 文件问题

**Comment by ntgeralt** [comment]
几点建议：
1：初次运行，可提示v2ray core应放在哪里，我们可以一步到位（最好core打包一起），
因为进去首选项，再一个个路径设置稍显冗长。

2：覆盖近旧版本时，旧节点信息自动读取过去。

3：点连接时，‘http入站未启用’的弹窗可省略掉，直接分流模式

添加 复制 删除 编辑 按钮，可再加一个读取剪贴板和扫描二维码。
日后扫描二维码可参考shadowrocket扫描订阅二维码也自动识别，那你软件基本非常容易上手了

**Comment by huyizheng** [comment]
> 新版本添加了 log 颜色（emmm 就是带颜色的 log）
> emmm 直接上图好了
> 
> ![image](https://user-images.githubusercontent.com/18734999/69789231-18472280-11fb-11ea-89f2-49426aa95bcc.png)

![图片](https://user-images.githubusercontent.com/22879638/69800504-5864d000-1210-11ea-9578-9925b4f4d4af.png)
这白底黄字完全看不清~

**Comment by lhy0403** [comment]
这个 @huyizheng 还没有对白色背景进行优化

**Comment by lhy0403** [comment]
> 1：初次运行，可提示v2ray core应放在哪里，我们可以一步到位（最好core打包一起），
> 因为进去首选项，再一个个路径设置稍显冗长。
目前没有打包 v2ray core 进发行版的打算（即使很简单）

 
> 2：覆盖旧版本时，旧节点信息自动读取过去。
这个我没太看懂，您能详细解释一下吗？

> 4：首选项更改https或pac设置后，服务自动断开再重连。
> 另外pac模式似乎有些问题。
这个是预期行为，需要重启 v2ray core 才能应用设置

> 添加 复制 删除 编辑 按钮，可再加一个读取剪贴板和扫描二维码。
> 日后扫描二维码可参考shadowrocket扫描订阅二维码也自动识别，那软件基本非常容易上手了
导入相关操作在 添加 窗口，不知道还有什么需要修改的

**Comment by ntgeralt** [comment]
@lhy0403 例如用户使用release新版时，节点需重新添加进去。我新版Qv2ray覆盖旧版发现没读取到旧节点，所以反馈下。

主机列表下面几个按钮，我发现对比v2rayn，你做了更直觉的方式。所以顺便建议下，读取剪贴板等也可做成按钮，从分页里放出来。

**Comment by lhy0403** [comment]
@ntgeralt 首先很感谢您的回复
你说的升级时意外丢失了config, 这个可能是一个bug,
将会在后续版本修复
😊

**Comment by lhy0403** [comment]
@lfxx 几小时前的 commit 修复了 PAC

**Comment by lhy0403** [comment]
@huyizheng 刚刚 dev 分支的 commit 添加了对于 light UI 的颜色支持，如果方便的话，请尝试一下

**Comment by lfxx** [comment]
> @lfxx 几小时前的 commit 修复了 PAC

好的,感谢大佬

**Comment by thebadgateway** [comment]
Windows - language switching does not work.

**Comment by lhy0403** [comment]
It’s extremely strange that you always failed to switch languages 😂@thebadgateway

**Comment by thebadgateway** [comment]
> It’s extremely strange that you always failed to switch languages @thebadgateway

Because I check the correctness of the translation. And switching languages does not work.

**Comment by thebadgateway** [comment]
![2019-11-30_23-32-27.png](https://pixs.ru/images/2019/11/30/2019-11-30_23-32-27.png)
I think it makes sense to shorten the prefix. Or move it after the server name. Or move and cut.

**Comment by lhy0403** [comment]
已添加基本订阅支持

**Comment by thebadgateway** [comment]
I think that we need a new option - automatic renewal of the subscription.

**Comment by thebadgateway** [comment]
The computer stayed on for the night. In the morning, the app freezes.

![5-DEK-2019--125545.png](https://pixs.ru/images/2019/12/05/5-DEK-2019--125545.png)

**Comment by lhy0403** [comment]
@thebadgateway Cool issue, will investigate then.

**Comment by lhy0403** [comment]
Did it take up nearly...... 1.2 GB memory? 
![image](https://user-images.githubusercontent.com/18734999/70206397-68296a80-1762-11ea-8bf6-992cb3bdd2f7.png)

**Comment by lhy0403** [comment]
It seems to be caused by the log widget.... I'll try to fix it this weekend.

**Comment by thebadgateway** [comment]
yep 1.2Gb

**Comment by lhy0403** [comment]
Closed due to releasing Qv2ray alpha 1,1
